//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesModel
{
    using System;
    
    public enum AddressType : int
    {
        Billing = 1,
        ShippingPrimary = 2,
        ShippingSecondary = 3
    }
}
